[[redirects]]
  from = "/firefox"
  to = "https://www.notion.so/brainbowstudio/Add-Sprinkles-to-Firefox-8b0fa54522034da1b881acf2e1adac4c"
[[redirects]]
  from = "/chrome"
  to = "https://chrome.google.com/webstore/detail/joofapp/knknjjghhkppgfkkclcdefohkfdnhfan"
